version: '3'

services: 
    web:
        build: .
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
        container_name: dockerize_django
        volumes: 
            - .:/dockerize_django
        ports:
            - "8000:8000"
            